### ISSUE TITLE
Support for PHP7 and PHPUnit 5.0?

### ISSUE THREAD

**Issue by kdambekalns** [mikey179/vfsStream#120] opened 2015-12-02 09:00 UTC
Now that PHP7 has been tagged and PHPUnit 5.0 is stable, are there any plans to make vfsStream compatible to those?

**Comment by mikey179** [comment] 2015-12-02 09:49
PHP7 compatibility should come in December, even though I don't think the current version is not compatible, at least the [tests didn't show a significant problem](https://travis-ci.org/mikey179/vfsStream/jobs/90189298) except for the output of a warning which is raised when simulating insufficient disk space, but that shouldn't effect most users.

Regarding PHPUnit 5.0 I don't see that there needs to be done anything about this. vfsStream has no runtime dependency to PHPUnit, and the dev dependency doesn't matter to users. If I'm not missing something here that shouldn't be a problem.

**Comment by kdambekalns** [comment] 2015-12-03 23:00
Well, didn't dig into it yet, but at least those "uninitialized strong offset" notices in https://travis-ci.org/kdambekalns/flow-development-collection/jobs/94757895 seem to be related to PHP7. Probably the "uniform variable access" changes, as far as we guess.

**Comment by mikey179** [comment] 2015-12-04 10:20
After digging into it I think it is not related to PHP 7, I was able to reproduce this with PHP 5.6.4. The problem is that the call to `vfsStream::setup()` passes a directory name with trailing slash, causing the `vfsStream::newDirectory()` method to create a directory instance with an empty name. I fixed this with 0ea19cb, a trailing slash will no longer cause the creation of such a directory instance.

**Comment by kdambekalns** [comment] 2015-12-04 10:26
I assumed it was related to PHP 7, since it didn't cause problems so far, but the code looks "broken" regardless of the PHP version. :-)

Anyway, thanks! Any chance to get a 1.6.1 tagged today?

**Comment by mikey179** [comment] 2015-12-04 12:05
Done, just released 1.6.1. I'll leave this issue open until PHP 7 compatibility is fully verified.

**Comment by kdambekalns** [comment] 2015-12-04 13:57
Thanks! For us it works so far…

**Comment by mikey179** [comment] 2016-01-05 15:44
There is stil a problem with a bug in PHP 7 itself: https://bugs.php.net/bug.php?id=71287

**Comment by mikey179** [comment] 2016-01-11 15:22
The bug is fixed in PHP 7.0.3.

**Closed** 2016-03-23 13:24 UTC
Labels: task
