### ISSUE TITLE
DirectoryIterator throws Exception with vfstream subfolder url

### ISSUE THREAD

**Issue by nix23** [mikey179/vfsStream#124] opened 2015-12-13 18:22 UTC
DirectoryIterator throws UnexpectedValueException when loaded vfs url contains subfolder.
Works:
````php
$root = vfsStream::setup("root");
$di = new \DirectoryIterator(vfsStream::url("root/");
// If some folders and files were added into root, we can iterate them here succesfully
````

Throws exception:
````php
$root = vfsStream::setup("root");
mkdir(vfsStream::url("root/child/");
// $di = new \DirectoryIterator(vfsStream::url("root/"); // Still works
$di = new \DirectoryIterator(vfsStream::url("root/child/"); // Throws Exception
````

Exception:
````php
UnexpectedValueException: DirectoryIterator::__construct(vfs://root/child): failed to open dir: "org\bovigo\vfs\vfsStreamWrapper::dir_opendir" call failed
````

PHP 5.6.14,

**Comment by mikey179** [comment] 2015-12-16 15:47
I can't reproduce this with vfsStream 1.6.1, neither on OS X with PHP 7 and PHP 5.6.4 nor on Debian with PHP 5.6.14. Executing the code doesn't throw an exception, but creates the `DirectoryIterator` instance. Do you have more details available, e.g. which version of vfsStream you are using?

**Comment by mikey179** [comment] 2016-04-09 09:51
Closing because I can't reproduce and no further feedback delivered. Please feel free to reopen when new information is available.

**Closed by mikey179** 2016-04-09 09:51 UTC
Labels: bug, feedback required

**Comment by rask** [comment] 2019-07-31 14:14
I got this error right now. Seems like this happens when you use a chmod value such as `2777`. Switching to `0777` made it work again. Could the error message be more clear in cases like these?

**Comment by allejo** [comment] 2019-08-01 02:04
@rask a value such as `2777` isn't valid to PHP's `chmod()`. According to the docs, it [requires that number to be an octal value](https://www.php.net/manual/en/function.chmod.php#refsect1-function.chmod-parameters); meaning it should be prefixed with a `0`.

Also, take a look at the [Notes](https://www.php.net/manual/en/function.chmod.php#refsect1-function.chmod-notes) section about setting SGIDs.

**Comment by rask** [comment] 2019-08-01 07:05
Yes, I was trying to set a bit that UNIXes support generally, and forgot that PHP does not support that with chmod. :)

**Comment by mikey179** [comment] 2019-08-01 08:52
I'm thinking about whether there should be a check in [vfsStreamAbstractContent::chmod()](https://github.com/bovigo/vfsStream/blob/master/src/main/php/org/bovigo/vfs/vfsStreamAbstractContent.php#L244) which throws an `UnexpectedValueException` in case a non-octal value is passed as argument so that such errors appear earlier and with a better error message. Improving the error message from `DirectoryIterator` like @rask suggested isn't possible as its thrown by PHP directly and can't be influenced by vfsStream.
